import React, { useEffect } from "react";
import { useLocation } from "react-router-dom";
import AppShell from "../components/app/AppShell";
import { Scale, ShieldCheck, FileText, Database } from "lucide-react";

/**
 * Legal — full screen consolidating Terms, Privacy, Licenses and the
 * Data Storage notice. Each section is anchored so the Account screen
 * can deep-link to a specific document via /legal#privacy, etc.
 */
export default function LegalScreen() {
  const { hash } = useLocation();
  useEffect(() => {
    if (!hash) return;
    const id = hash.replace(/^#/, "");
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });
  }, [hash]);
  return (
    <AppShell overline="Account" pageTitle="Legal">
      <div className="flex flex-col gap-4">
        <Section id="terms" icon={<Scale className="h-4 w-4" />} title="Terms of Use">
          <p>By using Trip Monitor — Driver Edition, you agree to operate the app in accordance with applicable trucking regulations and your motor carrier&apos;s policies.</p>
          <p>Trip sheets generated by the app are advisory; the driver of record is responsible for the accuracy of regulated entries (HOS, DVIRs, BOLs, scale tickets).</p>
          <p>Your local device data is yours. The app is provided &ldquo;as is&rdquo; with no warranty of fitness for any specific dispatch or audit workflow.</p>
        </Section>

        <Section id="privacy" icon={<ShieldCheck className="h-4 w-4" />} title="Privacy Policy">
          <p>Trip Monitor stores your driver profile, trip sheets and templates locally on your device. The backend mirrors only the minimum needed to render data across reinstalls.</p>
          <p>No biometric data ever leaves your device — fingerprint unlock is handled by the OS keychain. PII (name, license, contacts) is never sold or shared with third parties.</p>
          <p>You can export or delete your data at any time from Account → Account Actions.</p>
        </Section>

        <Section id="licenses" icon={<FileText className="h-4 w-4" />} title="Open-Source Licenses">
          <p>Trip Monitor uses React, FastAPI, Tailwind CSS, Radix UI, lucide-react and other open-source projects under MIT / BSD / Apache-2.0 licenses.</p>
          <p>A full attributions file is bundled with each release; tap App Information in Account to see the version and download the attributions.</p>
        </Section>

        <Section id="storage" icon={<Database className="h-4 w-4" />} title="Data Storage Notice">
          <p>Your saved Trip Monitor documents (BOLs, photos, receipts, exports, completed trip sheets) are stored separately from the app in the Trip Monitor folder you select.</p>
          <p>Deleting or uninstalling Trip Monitor will <span className="font-black">not</span> delete these files. To permanently remove them, manually delete the Trip Monitor folder from your device or external storage.</p>
        </Section>
      </div>
    </AppShell>
  );
}

function Section({ id, icon, title, children }) {
  return (
    <section
      id={id}
      data-testid={`legal-${id}`}
      className="bg-white border border-[var(--tm-border)] rounded-xl shadow-[0_2px_8px_rgba(14,31,71,0.04)]"
    >
      <header className="flex items-center gap-2 px-4 py-3 border-b border-[var(--tm-border)]">
        {icon}
        <h2 className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--tm-navy)]">{title}</h2>
      </header>
      <div className="px-4 py-4 flex flex-col gap-2 text-[13px] text-[var(--tm-navy)] font-semibold leading-relaxed">
        {children}
      </div>
    </section>
  );
}
